licensingservice:
  image: ch3-thoughtmechanix/licensing-service
  ports:
    - "8080:8080"
  environment:
    PROFILE: "dev"
    CONFIGSERVER_URI: http://configserver:8888
    CONFIGSERVER_PORT: "8888"
    DATABASESERVER_PORT: "5432"