tracer:
  property: "I AM THE DEFAULT ENVIRONMENT FOR PRODUCT MANAGEMENT SERVICE"

# DATA BASE CONFIGURATION
spring:
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    platform: "mysql"
    url: "jdbc:mysql://localhost:3306/sics_db?useSSL=false&serverTimezone=UTC"
    username: "landeros"
    password: "{cipher}9d0c276de4252fcbc180852183e88486c9f522e5c50fe18cdab434d613af5f10"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  
  jpa:
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: "update"

# HYSTRIX CONFIGURATION
hystrix:
  command:
    # Valores globales para toda la aplicacion, para los metodos con la anotacion @HystrixCommand
    default:
      execution.isolation.thread.timeoutInMilliseconds: 1000
      circuitBreaker.requestVolumeThreshold: 20
      circuitBreaker.errorThresholdPercentage: 50
      circuitBreaker.sleepWindowInMilliseconds: 5000
      metrics.rollingStats.timeInMilliseconds: 10000
      metrics.rollingStats.numBuckets: 10
    # Especifico para el metodo saveProsuctInStore el cual tiene la anotacion @HystrixCommand
    saveProductInStore:
      execution.isolation.thread.timeoutInMilliseconds: 100
  threadpool:
      saveProductInStoreThreadPool:
        coreSize: 30
        maxQueueSize: 10
